# Generated by Django 5.2.8 on 2025-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='roles',
            field=models.ManyToManyField(db_comment='Roles asignados para pacientes, profesional salud, recepcionista, laboratorista, adm centro', to='usuario.roles'),
        ),
    ]
