# Generated by Django 5.2.7 on 2025-11-19 02:27

# Plantilla de migración: RenameModel para mapear las clases antiguas (lowercase) a las nuevas (CamelCase).
# IMPORTANTE: ajusta la dependencia a la última migración existente en la app 'usuario'
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='administrativo',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'view only'), (2, 'create and modify')], default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='profesional_salud',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'view only'), (2, 'create and modify')], default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='usuario',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'view only'), (2, 'create and modify')], default=0),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuario', #REVISAR
        ),
    ]
