# Generated by Django 5.2.7 on 2025-12-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedades',
            name='categoria_grupom',
            field=models.CharField(blank=True, db_comment='refiere al grupo de mortalidad CIE10', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='enfermedades',
            name='codigo_cie10',
            field=models.CharField(db_comment='Codigo CIE-10 para clasificar diagnosticos, sintomas', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='enfermedades',
            name='grupo_mortalidad',
            field=models.CharField(blank=True, db_comment='de acuerdo con la CIE-10 ', max_length=250, null=True),
        ),
    ]
