# Generated by Django 5.2.8 on 2025-12-16 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='letra',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnos',
            name='creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(blank=True, db_comment='Estado: programada, atendido, etc', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(blank=True, db_column='id_paciente', db_comment='Referencia a PACIENTES', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.pacientes'),
        ),
    ]
