# Generated by Django 5.2.8 on 2025-12-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'managed': False},
        ),
    ]
