# Generated by Django 5.2.8 on 2025-11-24 01:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiracion', models.DateTimeField()),
            ],
        ),
    ]
