# Generated by Django 5.2.8 on 2025-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='ultimo_login',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='documento',
            field=models.CharField(blank=True, db_comment='Numero de documento del usuario', max_length=20, null=True),
        ),
    ]
