# Generated by Django 5.2.7 on 2025-11-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profesionalsalud',
            table='profesionalsalud',
        ),
    ]
