# Generated by Django 5.2.8 on 2025-12-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='via_administracion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='turnos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='letra',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='roles',
            field=models.ManyToManyField(db_comment='Roles asignados para pacientes, profesional salud, recepcionista, laboratorista, adm centro', to='usuario.roles'),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre_especialidad',
            field=models.CharField(db_comment='refiere a la especialidad medica: neurologia, cardiologia, etc', max_length=100, unique=0),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha de registro paciente', null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(blank=True, db_comment='Estado: programada, atendido, etc', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(blank=True, db_column='id_paciente', db_comment='Referencia a PACIENTES', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.pacientes'),
        ),
    ]
