# Generated by Django 5.2.8 on 2025-11-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
    ]
