# Generated by Django 5.2.8 on 2025-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_servicios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='numero_documento',
            field=models.CharField(blank=True, db_comment='Documento de identidad del usuario', max_length=20, null=True),
        ),
    ]
