# Generated by Django 5.2.8 on 2025-11-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuarios_id_rol_usuarios_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(blank=True, db_comment='Estado: programada, atendido, etc', max_length=10, null=True),
        ),
    ]
