# Generated by Django 5.2.8 on 2025-12-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_turnos_creado_turnos_letra_turnos_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='letra',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='numero',
        ),
        migrations.AlterField(
            model_name='turnos',
            name='creado_en',
            field=models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(blank=True, db_comment='Esta: programada, atendido, etc', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', db_comment='Referencia a PACIENTES', default=14, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.pacientes'),
            preserve_default=False,
        ),
    ]
