# Generated by Django 5.2.7 on 2025-11-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_roles_administrativo_roles_profesional_salud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', db_comment='Referencia a la cuenta de USUARIOS', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuarios'),
        ),
        migrations.AlterField(
            model_name='profesionalsalud',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', db_comment='Referencia a la cuenta de USUARIOS (Obligatorio para personal)', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuarios'),
        ),
    ]
