# Generated by Django 5.2.8 on 2025-11-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuarios_id_rol_usuarios_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='via_administracion',
        ),
    ]
