# Generated by Django 5.2.7 on 2025-12-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_enfermedades_categoria_grupom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrosmedicos',
            name='id_ciudad',
            field=models.ForeignKey(db_column='id_ciudad', db_comment='Referencia a CIUDAD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.ciudad'),
        ),
    ]
