# Generated by Django 5.2.7 on 2025-11-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_profesionalsalud_table'),
        ('usuario', '0002_remove_usuarios_id_rol_usuarios_roles'),
    ]

    operations = [
    ]
