# Generated by Django 5.2.8 on 2025-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_medicamentos_nombre_comercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='longitud',
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre_especialidad',
            field=models.CharField(db_comment='refiere a la especialidad medica: neurologia, cardiologia, etc', max_length=100, unique=0),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha de registro paciente', null=True),
        ),
    ]
