# Generated by Django 5.2.7 on 2025-11-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_pacientes_id_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='profesionalsalud',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
