# Generated by Django 5.2.8 on 2025-11-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_delete_turno_remove_turnos_creado_en_turnos_letra_and_more'),
    ]

    operations = [
    ]
