# Generated by Django 5.2.8 on 2025-11-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_afiliacion_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incapacidad',
            options={'managed': True},
        ),
    ]
