# Generated by Django 5.2.7 on 2025-12-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_medicamentos_nombre_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='roles',
            field=models.ManyToManyField(to='usuario.roles'),
        ),
    ]
