# Generated by Django 5.2.7 on 2025-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_merge_20251126_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios_con_rol', to='usuario.roles'),
        ),
    ]
