# Generated by Django 5.2.7 on 2025-12-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_centrosmedicos_id_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrosmedicos',
            name='id_nivel_atencion',
            field=models.ForeignKey(db_column='id_nivel_atencion', db_comment='Referencia a NIVELES_ATENCION', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.nivelesatencion'),
        ),
    ]
