# Generated by Django 5.2.7 on 2025-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_centrosmedicos_id_nivel_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='concentracion',
            field=models.CharField(blank=True, db_comment='Concentracion medicamento', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, db_comment='Forma farmaceutica medicamento', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='registro_invima',
            field=models.CharField(db_comment='Registro INVIMA del medicamento', max_length=300, unique=True),
        ),
    ]
