# Generated by Django 5.2.7 on 2025-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuarios_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmedica',
            name='pdf_archivo',
            field=models.BinaryField(blank=True, db_comment='PDF almacenado como bytes en PostgreSQL', null=True),
        ),
        migrations.AddField(
            model_name='ordenmedica',
            name='pdf_fecha_generacion',
            field=models.DateTimeField(blank=True, db_comment='Fecha de generación del PDF', null=True),
        ),
    ]
