# Generated by Django 5.2.8 on 2025-12-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_centrosmedicos_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='numero_documento',
            field=models.CharField(blank=True, db_comment='Documento de identidad del usuario', max_length=20, null=True),
        ),
    ]
