# Generated by Django 5.2.7 on 2025-12-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuarios_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedades',
            name='categoria',
        ),
        migrations.AddField(
            model_name='enfermedades',
            name='categoria_grupom',
            field=models.CharField(blank=True, db_comment='refiere al grupo de mortalidad CIE10', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enfermedades',
            name='grupo_mortalidad',
            field=models.CharField(blank=True, db_comment='de acuerdo con la CIE-10 ', max_length=50, null=True),
        ),
    ]
