# Generated by Django 5.2.7 on 2025-11-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_id_usuario_pacientes_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
