# Generated by Django 5.2.8 on 2025-11-27 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_delete_turno_turnos_creado_turnos_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='id_paciente',
            field=models.ForeignKey(blank=True, db_column='id_paciente', db_comment='Referencia a PACIENTES', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.pacientes'),
        ),
    ]
