# Generated by Django 5.2.7 on 2025-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_medicamentos_concentracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='principio_activo',
            field=models.CharField(blank=True, db_comment='Principio activo medicamento', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='registro_invima',
            field=models.CharField(db_comment='Registro INVIMA del medicamento', max_length=500, unique=True),
        ),
    ]
