# Generated by Django 5.2.7 on 2025-11-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuarios_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='rol',
            new_name='id_rol',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='administrativo',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='profesional_salud',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ultimo_login',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
