# Generated by Django 5.2.7 on 2025-12-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_enfermedades_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedades',
            name='codigo_cie10',
            field=models.CharField(db_comment='Codigo CIE-10 para clasificar diagnosticos, sintomas', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enfermedades',
            name='grupo_mortalidad',
            field=models.CharField(blank=True, db_comment='de acuerdo con la CIE-10 ', max_length=150, null=True),
        ),
    ]
