# Generated by Django 5.2.7 on 2025-12-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_enfermedades_codigo_cie10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='principio_activo',
            field=models.CharField(blank=True, db_comment='Principio activo medicamento', max_length=300, null=True),
        ),
    ]
