# Generated by Django 5.2.8 on 2025-12-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_centrosmedicos_latitud_and_more'),
        ('usuario', '0006_delete_turno_alter_turnos_id_paciente'),
    ]

    operations = [
    ]
