# Generated by Django 5.2.7 on 2025-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_rename_rol_usuarios_id_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='identificacion',
            field=models.CharField(db_comment='Abreviatura del tipo de identificacion: CC, TI, etc', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='nombre_identificacion',
            field=models.CharField(db_comment='Nombre completo del tipo de identificacion: Cédula de Ciudadanía, Tarjeta de Identidad, etc', max_length=50),
        ),
    ]
