# Generated by Django 5.2.7 on 2025-12-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_medicamentos_principio_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenmedica',
            name='id_medicamento',
            field=models.ForeignKey(blank=True, db_column='id_medicamento', db_comment='Referencia a MEDICAMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.medicamentos'),
        ),
        migrations.AlterField(
            model_name='ordenmedica',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', db_comment='Referencia a PACIENTE', on_delete=django.db.models.deletion.CASCADE, to='usuario.pacientes'),
        ),
        migrations.AlterField(
            model_name='ordenmedica',
            name='id_profesional',
            field=models.ForeignKey(db_column='id_profesional', db_comment='Referencia a PROFESIONAL_SALUD', on_delete=django.db.models.deletion.CASCADE, to='usuario.profesionalsalud'),
        ),
        migrations.AlterField(
            model_name='ordenmedica',
            name='id_servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', db_comment='Referencia a SERVICIOS', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.servicios'),
        ),
        migrations.AlterField(
            model_name='ordenmedica',
            name='id_tipo_orden',
            field=models.ForeignKey(db_column='id_tipo_orden', db_comment='Referencia a TIPO_ORDEN', on_delete=django.db.models.deletion.CASCADE, to='usuario.tipoorden'),
        ),
    ]
