# Generated by Django 5.2.7 on 2025-12-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_medicamentos_principio_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='nivel_formacion',
        ),
    ]
