# Generated by Django 5.2.7 on 2025-12-10 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_ordenmedica_id_medicamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmedica',
            name='id_lote',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador para agrupar órdenes de un mismo lote.'),
        ),
    ]
