# Generated by Django 5.2.7 on 2025-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_ordenmedica_id_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='tipo_antecedente',
            field=models.CharField(choices=[('Familiar', 'Familiar'), ('Personal', 'Personal'), ('Laboral', 'Laboral')], db_comment='si es: familiar, personal, etc', max_length=50),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='habitos_alcohol',
            field=models.CharField(blank=True, db_comment='Consume alcohol', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='habitos_ejercicio',
            field=models.CharField(blank=True, db_comment='Realiza actividad fisica', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='habitos_fumador',
            field=models.CharField(blank=True, db_comment='Fuma', max_length=50, null=True),
        ),
    ]
