# Generated by Django 5.2.7 on 2025-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_especialidades_nivel_formacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='codigo_habilitacion',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='estado_centro',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='fecha_habilitacion',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='centrosmedicos',
            name='sitio_web',
        ),
        migrations.AlterField(
            model_name='centrosmedicos',
            name='celular',
            field=models.CharField(blank=True, db_comment='Celular centro medico', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='centrosmedicos',
            name='telefono',
            field=models.CharField(blank=True, db_comment='Telefono centro medico', max_length=60, null=True),
        ),
    ]
