# Generated by Django 5.2.7 on 2025-12-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_centrosmedicos_codigo_habilitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha de registro paciente', null=True),
        ),
    ]
