# Generated by Django 5.2.7 on 2025-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_pacientes_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='estado_antecedente',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Resuelto', 'Resuelto'), ('Pendiente', 'Pendiente')], db_comment='Esta: activo, resuelto, etc', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='severidad',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Alta', 'Alta')], db_comment='es: leve, moderada, etc', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='tipo_antecedente',
            field=models.CharField(choices=[('Familiar', 'Familiar'), ('Personal', 'Personal'), ('Laboral', 'Laboral')], db_comment='si es: familiar, personal, etc', max_length=13),
        ),
    ]
