# Generated by Django 5.2.7 on 2025-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_antecedentespaciente_tipo_antecedente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoslaboratorio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='resultadoslaboratorio',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='resultadoslaboratorio',
            name='tipo_examen',
        ),
        migrations.AddField(
            model_name='resultadoslaboratorio',
            name='observaciones_resultados',
            field=models.TextField(blank=True, db_comment='Notas adicionales a los resultados laboratorio', null=True),
        ),
    ]
