# Generated by Django 5.2.7 on 2025-12-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_remove_resultadoslaboratorio_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoslaboratorio',
            name='id_servicio',
        ),
    ]
