# Generated by Django 5.2.7 on 2025-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_remove_resultadoslaboratorio_id_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoslaboratorio',
            old_name='fecha_resultado',
            new_name='fecha_registro_resultado',
        ),
        migrations.AddField(
            model_name='resultadoslaboratorio',
            name='archivo_pdf',
            field=models.FileField(blank=True, db_comment='Archivo PDF con el resultado', null=True, upload_to='resultados_laboratorio/'),
        ),
    ]
