"""
Django settings for unisalud project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar .env asegurando UTF-8 y forzar codificación cliente Postgres antes de conectar
load_dotenv(dotenv_path=BASE_DIR / '.env', encoding='utf-8')
os.environ.setdefault('PGCLIENTENCODING', 'UTF8')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-!l-yc9h$9on^#lc(v6&e7^divqoj%$-o7h4e$-pc^b$ovcq@#7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.1.40').split(',')

# Dominio base para construir URLs absolutas (para QR, correos, etc.)
# En desarrollo, usa la IP de tu máquina en la red local. Ej: 'http://192.168.1.10:8000'
# En producción, será tu dominio real. Ej: 'https://www.unisalud.com'
BASE_DOMAIN = os.getenv('BASE_DOMAIN', 'http://192.168.1.40:8000') #WIFI CASA
# Permitir que las vistas se carguen en iframes del mismo dominio
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuario',
    'prof_salud',
    'administrativo',
    'login',
    'rLaboratorio',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'unisalud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'usuario', 'profesionalS', 'templates')], #DIRS: [] estaba antes vacio
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'unisalud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'unisaludBD',  # Nombre de la BD
        'USER': 'admin',  # Usuario de MySQL
        'PASSWORD': 'unisaludBD*',  # Cambia por tu contraseña
        'HOST': 'localhost',  # Servidor de BD
        'PORT': '5432',  # Puerto de MySQL (por defecto)
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (User-uploaded files)
# Directorio donde se guardarán los archivos subidos por los usuarios.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# CONFIGURACIÓN PARA ENVÍO DE CORREO ELECTRÓNICO
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Servidor SMTP de Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tu_correo@gmail.com'  # Tu dirección de correo de Gmail
EMAIL_HOST_PASSWORD = 'tu_contraseña_de_aplicacion' # NO es tu contraseña normal, es una contraseña de aplicación
DEFAULT_FROM_EMAIL = 'tu_correo@gmail.com'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
