# Generated by Django 5.2.8 on 2025-11-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id_afiliacion', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_comment='Fecha de inicio afliacion')),
                ('fecha_fin', models.DateField(blank=True, db_comment='Fecha de fin de la afiliacion', null=True)),
                ('estado_afiliacion', models.CharField(blank=True, db_comment='Esta: activo, inactiva', max_length=10, null=True)),
            ],
            options={
                'db_table': 'AFILIACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesPaciente',
            fields=[
                ('id_antecedente', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('tipo_antecedente', models.CharField(db_comment='si es: familiar, personal, etc', max_length=13)),
                ('descripcion', models.TextField(db_comment='Descripcion')),
                ('fecha_registro', models.DateField(blank=True, db_comment='Fecha de registro', null=True)),
                ('severidad', models.CharField(blank=True, db_comment='es: leve, moderada, etc', max_length=8, null=True)),
                ('estado_antecedente', models.CharField(blank=True, db_comment='Esta: activo, resuelto, etc', max_length=14, null=True)),
            ],
            options={
                'db_table': 'ANTECEDENTES_PACIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentrosMedicos',
            fields=[
                ('id_centro_medico', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(db_comment='Nombre del centro medico', max_length=150)),
                ('direccion', models.CharField(db_comment='Direccion centro medico', max_length=255)),
                ('latitud', models.DecimalField(blank=True, db_comment='Latitud, localizacion geografica', decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, db_comment='Longitud, localizacion geografica', decimal_places=8, max_digits=10, null=True)),
                ('telefono', models.CharField(blank=True, db_comment='Telefono centro medico', max_length=15, null=True)),
                ('celular', models.CharField(blank=True, db_comment='Celular centro medico', max_length=15, null=True)),
                ('correo', models.CharField(blank=True, db_comment='Correo entro medico', max_length=100, null=True)),
                ('sitio_web', models.CharField(blank=True, db_comment='Sitio web centro medico', max_length=150, null=True)),
                ('codigo_habilitacion', models.CharField(blank=True, db_comment='Codigo de habilitacion REPS', max_length=50, null=True, unique=True)),
                ('fecha_habilitacion', models.DateField(blank=True, db_comment='Fecha de habilitacion REPS', null=True)),
                ('estado_centro', models.CharField(blank=True, db_comment='Esta activa, inactiva', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CENTROS_MEDICOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(db_comment='Nombre de la ciudad', max_length=100)),
                ('codigo_dane', models.CharField(blank=True, db_comment='Codigo DANE para identificar oficialmente c-ciudad', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CIUDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_comment='Esta: programada, atendido, etc', max_length=10, null=True)),
                ('fecha_programada', models.DateTimeField(db_comment='Fecha programada la consulta')),
                ('fecha_atencion', models.DateTimeField(blank=True, db_comment='Fecha de atencion consulta', null=True)),
                ('motivo_consulta', models.TextField(blank=True, db_comment='Motivo por la que el paciente asiste a la consulta', null=True)),
                ('anamnesis', models.TextField(blank=True, db_comment='informacion que aporta el paciente para crear el historial clinico', null=True)),
                ('examen_fisico', models.TextField(blank=True, db_comment='Examen fisico, exploratorio al paciente', null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, db_comment='FC en lpm', null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, db_comment='FR en rpm', null=True)),
                ('temperatura', models.DecimalField(blank=True, db_comment='Temperatura en grados C', decimal_places=2, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, db_comment='SpO2 en porcentaje', null=True)),
                ('presion_arterial_sistolica', models.IntegerField(blank=True, db_comment='TA sistolica', null=True)),
                ('presion_arterial_diastolica', models.IntegerField(blank=True, db_comment='TA diastolica', null=True)),
                ('peso', models.DecimalField(blank=True, db_comment='Peso en kg', decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, db_comment='Talla en cm', decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, db_comment='Indice de Masa Corporal', decimal_places=2, max_digits=4, null=True)),
                ('habitos_fumador', models.CharField(blank=True, db_comment='Fuma', max_length=9, null=True)),
                ('habitos_alcohol', models.CharField(blank=True, db_comment='Consume alcohol', max_length=9, null=True)),
                ('habitos_ejercicio', models.CharField(blank=True, db_comment='Realiza actividad fisica', max_length=2, null=True)),
                ('revision_sistemas', models.TextField(blank=True, db_comment='Revision por sistemas', null=True)),
                ('impresion_diagnostica', models.TextField(blank=True, db_comment='Diagnostico al paciente', null=True)),
                ('plan_tratamiento', models.TextField(blank=True, db_comment='Plan de tratamiento para el paciente', null=True)),
                ('notas_adicionales', models.TextField(blank=True, db_comment='Notas del profesional salud, opcional', null=True)),
                ('creado_en', models.DateTimeField(blank=True, db_comment='Fecha de registro de la consulta', null=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'CONSULTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(db_comment='Nombre del departamento', max_length=100)),
                ('codigo_dane', models.CharField(blank=True, db_comment='Codigo DANE para identificar oficialmente c-depto.', max_length=10, null=True)),
            ],
            options={
                'db_table': 'DEPARTAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleMedicamento',
            fields=[
                ('id_detalle', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('lote', models.CharField(db_comment='Numero de lote medicamento', max_length=50)),
                ('fecha_expiracion', models.DateField(db_comment='Fecha de vencimiento medicamento')),
                ('condiciones_almacenamiento', models.TextField(blank=True, db_comment='Condiciones de almacenamiento medicamento', null=True)),
                ('cantidad_existente', models.IntegerField(blank=True, db_comment='Cantidad disponible medicamento', null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_comment='Fecha de ingreso medicamento', null=True)),
                ('estado', models.CharField(blank=True, db_comment='Estado del lote: activo, agotado, etc', max_length=8, null=True)),
            ],
            options={
                'db_table': 'DETALLE_MEDICAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoPaciente',
            fields=[
                ('id_diagnostico', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('tipo_diagnostico', models.CharField(blank=True, db_comment='Es: presuntivo, principal, etc', max_length=10, null=True)),
                ('notas', models.TextField(blank=True, db_comment='Notas', null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
            ],
            options={
                'db_table': 'DIAGNOSTICO_PACIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id_enfermedad', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('codigo_cie10', models.CharField(db_comment='Codigo CIE-10 para clasificar diagnosticos, sintomas', max_length=10, unique=True)),
                ('nombre_enfermedad', models.CharField(db_comment='Nombre de la enfermedad', max_length=300)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion clinica de la enfermedad', null=True)),
                ('categoria', models.CharField(blank=True, db_comment='refiere si es aguda, cronica, infecciosa, etc', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ENFERMEDADES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_eps', models.CharField(db_comment='Nombre de la EPS', max_length=100, unique=True)),
                ('nit', models.CharField(blank=True, db_comment='NIT de la EPS', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_comment='Direccion de la EPS', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_comment='Telefono de la EPS', max_length=15, null=True)),
                ('correo', models.CharField(blank=True, db_comment='Correo de la EPS', max_length=100, null=True)),
                ('estado_eps', models.CharField(blank=True, db_comment='Esta activa, inactiva', max_length=8, null=True)),
            ],
            options={
                'db_table': 'EPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidad', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(db_comment='refiere a la especialidad medica: neurologia, cardiologia, etc', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion', null=True)),
                ('nivel_formacion', models.CharField(blank=True, db_comment='Nivel de formacion', max_length=15, null=True)),
            ],
            options={
                'db_table': 'ESPECIALIDADES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(db_comment='Ej: soltero, casado, etc', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'ESTADO_CIVIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id_estado_orden', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_estado_orden', models.CharField(db_comment='esta: pendiente, entregada, etc', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'ESTADO_ORDEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstratoSocioeconomico',
            fields=[
                ('id_estrato', models.IntegerField(db_comment='ID del 1 al 6', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_comment='Ej: Bajo, Medio, alto', max_length=100)),
            ],
            options={
                'db_table': 'ESTRATO_SOCIOECONOMICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(db_comment='Ej: Masculino, Femenino, No Binario, etc', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'GENERO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoRh',
            fields=[
                ('id_rh', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('tipo_rh', models.CharField(db_comment='Ej: A+, B-, etc', max_length=3, unique=True)),
            ],
            options={
                'db_table': 'GRUPO_RH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id_incapacidad', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_comment='Fecha de inicio de la incapacidad')),
                ('fecha_fin', models.DateField(db_comment='Fecha de fin de la incapacidad')),
                ('dias_incapacidad', models.IntegerField(blank=True, db_comment='Dias totales de la incapacidad', null=True)),
                ('motivo', models.TextField(db_comment='Motivo de la incapacidad')),
                ('diagnostico_relacionado', models.TextField(blank=True, db_comment='Diagnostico que justifica la incapacidad', null=True)),
                ('observaciones', models.TextField(blank=True, db_comment='Notas adicionales', null=True)),
                ('estado', models.CharField(blank=True, db_comment='Esta: activa, finalizada, etc', max_length=10, null=True)),
                ('codigo_qr', models.CharField(blank=True, db_comment='Codigo QR para descarga de la incapacidad', max_length=255, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, db_comment='Fecha de emision incapacidad', null=True)),
            ],
            options={
                'db_table': 'INCAPACIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(db_comment='Nombre comercial medicamento', max_length=200)),
                ('nombre_generico', models.CharField(blank=True, db_comment='Nombre generico medicamento', max_length=200, null=True)),
                ('principio_activo', models.CharField(blank=True, db_comment='Principio activo medicamento', max_length=100, null=True)),
                ('concentracion', models.CharField(blank=True, db_comment='Concentracion medicamento', max_length=50, null=True)),
                ('forma_farmaceutica', models.CharField(blank=True, db_comment='Forma farmaceutica medicamento', max_length=50, null=True)),
                ('via_administracion', models.CharField(blank=True, db_comment='Via de administracion medicamento', max_length=50, null=True)),
                ('registro_invima', models.CharField(db_comment='Registro INVIMA del medicamento', max_length=100, unique=True)),
                ('fabricante', models.CharField(blank=True, db_comment='Fabricante del medicamento', max_length=150, null=True)),
                ('estado_medicamento', models.CharField(blank=True, db_comment='Esta activo, retirado, etc', max_length=11, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_comment='Fecha de registro medicamento', null=True)),
            ],
            options={
                'db_table': 'MEDICAMENTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelesAtencion',
            fields=[
                ('id_nivel', models.IntegerField(db_comment='ID del nivel (1 a 3)', primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(db_comment='de acuerdo al grado de complejidad en salud: primer nivel-atencion basica', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion', null=True)),
            ],
            options={
                'db_table': 'NIVELES_ATENCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id_orden', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('dosis', models.CharField(blank=True, db_comment='Dosis del medicamento', max_length=100, null=True)),
                ('duracion_tratamiento', models.CharField(blank=True, db_comment='De acuerdo al diagnostico', max_length=100, null=True)),
                ('frecuencia', models.CharField(blank=True, db_comment='Frecuencia de acuerdo al diagnostico', max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_comment='Cantidad de acuerdo al diagnostico', null=True)),
                ('indicaciones', models.TextField(blank=True, db_comment='Indicaciones tratamiento y-o procedimiento', null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, db_comment='Fecha de emision de la orden', null=True)),
                ('fecha_cumplimiento', models.DateTimeField(blank=True, db_comment='Fecha de cumplimiento, maximo 30 dias', null=True)),
                ('codigo_qr', models.CharField(blank=True, db_comment='Codigo QR para descarga segura', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Orden Medica',
                'verbose_name_plural': 'Ordenes Medicas',
                'db_table': 'ORDEN_MEDICA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(db_comment='Numero del documento paciente', max_length=20)),
                ('nombre1', models.CharField(db_comment='Primer nombre paciente', max_length=50)),
                ('nombre2', models.CharField(blank=True, db_comment='Segundo nombre paciente, opcional', max_length=50, null=True)),
                ('apellido1', models.CharField(db_comment='Primer apellido paciente', max_length=50)),
                ('apellido2', models.CharField(blank=True, db_comment='Segundo apellido paciente, opcional', max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(db_comment='Fecha de nacimiento paciente')),
                ('direccion', models.CharField(blank=True, db_comment='Direccion paciente', max_length=255, null=True)),
                ('celular', models.CharField(blank=True, db_comment='Celular paciente', max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, db_comment='Telefono fijo paciente, opcional', max_length=15, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_comment='Correo paciente, opcional', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_comment='Fecha de registro paciente', null=True)),
            ],
            options={
                'db_table': 'PACIENTES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('id_profesional', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(db_comment='Numero del documento profesional salud', max_length=20)),
                ('nombre1', models.CharField(db_comment='Primer nombre profesional salud', max_length=50)),
                ('nombre2', models.CharField(blank=True, db_comment='Segundo nombre profesional salud', max_length=50, null=True)),
                ('apellido1', models.CharField(db_comment='Primer apellido profesional salud', max_length=50)),
                ('apellido2', models.CharField(blank=True, db_comment='Segundo apellido profesional salud', max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_comment='Fecha de nacimiento profesional salud', null=True)),
                ('telefono', models.CharField(blank=True, db_comment='Telefono profesional salud, opcional', max_length=15, null=True)),
                ('celular', models.CharField(blank=True, db_comment='Celular profesional salud', max_length=15, null=True)),
                ('correo', models.CharField(blank=True, db_comment='Correo profesional salud', max_length=100, null=True)),
                ('registro_profesional', models.CharField(blank=True, db_comment='Registro medico, puede ser NULL para recepcionistas-admins', max_length=50, null=True, unique=True)),
                ('fecha_vinculacion', models.DateField(blank=True, db_comment='Fecha de vinculacion', null=True)),
                ('estado', models.CharField(blank=True, db_comment='Esta: activo, inactivo, etc', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Profesional de Salud',
                'verbose_name_plural': 'Profesionales de Salud',
                'db_table': 'PROFESIONAL_SALUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedesSalud',
            fields=[
                ('id_red', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_red', models.CharField(db_comment='Nombre de la red: RIPSS (Redes integrales de prestadores de servicios de salud)', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion', null=True)),
                ('estado_red', models.CharField(blank=True, db_comment='Esta activa, inactiva', max_length=8, null=True)),
            ],
            options={
                'db_table': 'REDES_SALUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionSalud',
            fields=[
                ('id_region', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(db_comment='Nombre de la region Ej: caribe, eje cafetero, sur occidente, etc', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion', null=True)),
            ],
            options={
                'db_table': 'REGION_SALUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadosLaboratorio',
            fields=[
                ('id_resultado', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(db_comment='Fecha en que se solicito el examen')),
                ('fecha_resultado', models.DateTimeField(blank=True, db_comment='Fecha en que se registro el resultado', null=True)),
                ('tipo_examen', models.CharField(db_comment='tipo de examenes solicitados', max_length=200)),
                ('resultado', models.TextField(db_comment='Resultados de los examenes de laboratorio')),
                ('observaciones', models.TextField(blank=True, db_comment='Notas adicionales', null=True)),
                ('estado', models.CharField(blank=True, db_comment='Esta: pendiente, registrado, etc', max_length=10, null=True)),
                ('codigo_qr', models.CharField(blank=True, db_comment='Codigo QR para descarga', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
            ],
            options={
                'db_table': 'RESULTADOS_LABORATORIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(db_comment='ID autoincremental del roles', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_comment='Nombre de los roles: paciente, profesional_salud, laboratorista, recepcionista, admin_centro_medico', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion de los roles para mayor claridad, opcional', null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(db_comment='ID autoincremental del servicio', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_comment='Nombre del servicio medico', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion detallada del servicio medico', null=True)),
                ('tipo_servicio', models.CharField(db_comment='Categoria: imagenologia, laboratorio, etc', max_length=21)),
                ('estado', models.CharField(blank=True, db_comment='Esta activo, inactivo, etc', max_length=10, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_comment='Fecha de creacion', null=True)),
            ],
            options={
                'db_table': 'SERVICIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipo_identificacion', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('identificacion', models.CharField(db_comment='Tipo de identificacion: cedula, tarjeta, etc', max_length=50, unique=True)),
                ('nombre_identificacion', models.CharField(db_comment='Nombre de la abreviatura, CC: cedula de ciudadania', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripcion opcional', null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Identificacion',
                'verbose_name_plural': 'Tipos de Identificacion',
                'db_table': 'TIPO_IDENTIFICACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id_tipo', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_comment='Es: Medicamentos, examenes, etc', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'TIPO_ORDEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposAfiliacion',
            fields=[
                ('id_tipo_afiliacion', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_comment='el paciente esta en regimen Contributivo, Subsidiado, etc', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'TIPOS_AFILIACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(db_comment='ID autoincremental', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, db_comment='Esta: programada, atendido, etc', max_length=10, null=True)),
                ('fecha_hora_turno', models.DateTimeField(db_comment='Fecha y hora de la asignacion del turno')),
                ('solicitud_turno', models.CharField(blank=True, db_comment='Solicitado a partir de los 10m del centro medico', max_length=8, null=True)),
                ('categoria_turno', models.CharField(blank=True, db_comment='El paciente escoge la opcion', max_length=19, null=True)),
                ('modulo_asignado', models.CharField(blank=True, db_comment='Modulo asignado: Facturacion, Laboratorios, Atencion, etc', max_length=100, null=True)),
                ('creado_en', models.DateTimeField(blank=True, db_comment='Fecha de registro', null=True)),
            ],
            options={
                'db_table': 'TURNOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(db_comment='ID autoincremental del usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_comment='Login unico para el usuario', max_length=50, unique=True)),
                ('contrasena', models.CharField(db_comment='Contrasena que crea el usuario', max_length=255)),
                ('email', models.CharField(blank=True, db_comment='Correo principal-login del usuario', max_length=100, null=True, unique=True)),
                ('ultimo_login', models.DateTimeField(blank=True, db_comment='ultimo inicio de sesion', null=True)),
                ('estado', models.CharField(blank=True, db_comment='Esta: activo, inactivo,etc', max_length=9, null=True)),
            ],
            options={
                'db_table': 'USUARIOS',
                'managed': False,
            },
        ),
    ]
