# Generated by Django 5.2.8 on 2025-11-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof_salud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afiliacion',
        ),
        migrations.DeleteModel(
            name='AntecedentesPaciente',
        ),
        migrations.DeleteModel(
            name='CentrosMedicos',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='DetalleMedicamento',
        ),
        migrations.DeleteModel(
            name='DiagnosticoPaciente',
        ),
        migrations.DeleteModel(
            name='Enfermedades',
        ),
        migrations.DeleteModel(
            name='Eps',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
        migrations.DeleteModel(
            name='EstadoOrden',
        ),
        migrations.DeleteModel(
            name='EstratoSocioeconomico',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='GrupoRh',
        ),
        migrations.DeleteModel(
            name='Incapacidad',
        ),
        migrations.DeleteModel(
            name='Medicamentos',
        ),
        migrations.DeleteModel(
            name='NivelesAtencion',
        ),
        migrations.DeleteModel(
            name='OrdenMedica',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
        migrations.DeleteModel(
            name='ProfesionalSalud',
        ),
        migrations.DeleteModel(
            name='RedesSalud',
        ),
        migrations.DeleteModel(
            name='RegionSalud',
        ),
        migrations.DeleteModel(
            name='ResultadosLaboratorio',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='TipoIdentificacion',
        ),
        migrations.DeleteModel(
            name='TipoOrden',
        ),
        migrations.DeleteModel(
            name='TiposAfiliacion',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
